---
title: "Old Lyme Ospreys - 2020 Review"
description: |
  A short description of the post.
author:
  - name: Alex Clippinger
    url: {}
date: 09-20-2021
output:
  distill::distill_article:
    self_contained: false
preview: images/ct-audobon-logo.png
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(here)
library(janitor)
```

This blog is a quick look at the 2020 Osprey Nation Report by the Connecticut Audobon Society, released on March 5, 2021. 

Source: https://www.ctaudubon.org/osprey-nation-home/


Let's take a look at the data:

```{r}
# Load all nests dataset
all_nests <- read.csv(file = "data/All_Nests.csv") %>% 
  clean_names() %>% 
  rename("x2021_status" = 19) %>% 
  select(-(description:icon))

# load old lyme data only
ol_nests <- read.csv(file = "data/OL-Only_Nests.csv") %>% 
  clean_names() %>% 
  rename("x2021_status" = 19) %>% 
  select(-(descriptio:icon))
```

```{r}
all_nests_monitored <- all_nests %>% 
  
  # select only monitored status column
  select(monitored_y_n) %>% 
  
  # count by monitored status
  group_by(monitored_y_n) %>% 
  summarize(count = n())

ggplot(data = all_nests_monitored, aes(x = count, y = monitored_y_n)) +
  geom_col() + 
  theme_minimal()
```

```{r}
ol_nests_monitored <- ol_nests %>% 
  
  # select only monitored status column
  select(monitored) %>% 
  
  # count by monitored status
  group_by(monitored) %>% 
  summarize(count = n())

ggplot(data = ol_nests_monitored, aes(x = count, y = monitored)) +
  geom_col() + 
  theme_minimal()
```

```{r}
all_nest_types <- all_nests %>% 
  
  # select only nest type column
  select(nest_type) %>% 
  
  # aggregate strings with different cases and white space
  mutate(nest_type = tolower(nest_type)) %>% 
  mutate(nest_type = trimws(nest_type)) %>% 
  
  # count by nest type
  group_by(nest_type) %>% 
  summarize(count = n()) %>% 
  
  # only show top 10 most common nest types
  arrange(desc(count)) %>% 
  slice(1:10)

ggplot(data = all_nest_types, aes(x = count, y = nest_type)) +
  geom_col() +
  theme_minimal()

```

```{r}
ol_nest_types <- ol_nests %>% 
  
  # select only nest type column
  select(nest_type) %>% 
  
  # aggregate strings with different cases and white space
  mutate(nest_type = tolower(nest_type)) %>% 
  mutate(nest_type = trimws(nest_type)) %>% 
  
  # count by nest type
  group_by(nest_type) %>% 
  summarize(count = n()) %>% 
  
  # arrange by count desc
  arrange(desc(count))

ggplot(data = ol_nest_types, aes(x = count, y = nest_type)) +
  geom_col() +
  theme_minimal()

```


```{r}
all_nests_status <- all_nests %>% 
  
  # select only 2021 status column
  select(x2021_status) %>% 
  
  # count by nest status
  group_by(x2021_status) %>% 
  summarize(count = n())

ggplot(data = all_nests_status, aes(x = count, y = x2021_status)) +
  geom_col() +
  theme_minimal()
```

```{r}
ol_nests_status <- ol_nests %>% 
  
  # select only 2021 status column
  select(x2021_status) %>% 
  
  # count by nest status
  group_by(x2021_status) %>% 
  summarize(count = n())

ggplot(data = ol_nests_status, aes(x = count, y = x2021_status)) +
  geom_col() +
  theme_minimal()
```













