---
title: "Alex Clippinger"
image: "alex.jfif"
links:
  - label: '<i class="fab fa-linkedin"></i> LinkedIn'
    url: "https://www.linkedin.com/in/alex-clippinger"
  - label: '<i class="fab fa-github"></i> GitHub'
    url: "https://github.com/alexclippinger"
  - label: '<i class="fa fa-envelope" aria-hidden="true"></i> Email'
    url: "mailto:alexclippinger@ucsb.edu"
output:
  postcards::trestles
site: distill::distill_website
---

### About Me

I graduated from Northeastern University in Boston, MA in 2019 with a Bachelor’s Degree in Mathematics and Economics. After college, I spent the next year working in catastrophe risk modeling, where I gained exposure to the applications of data science to environmental applications. I earned a Graduate Certificate in Geographic Information Systems (GIS) in 2021 and began pursuing a career combining environmental science and data. Most recently, I was a geospatial analyst at Sentera, where I used GIS, remote sensing, and machine learning tools to analyze in-season agriculture data from drone imagery. As a Master of Environmental Data Science (MEDS) student at the UCSB Bren School of Environmental Science and Management, I hope to learn the necessary skills to take on difficult environmental challenges with an increasing demand for data-intensive solutions.
<br />
<br />

#### Education

**Master of Environmental Data Science** (Expected June 2022), Bren School of Environmental Science & Management, University of California, Santa Barbara - Santa Barbara, CA

**Graduate Certificate** (April 2021), Northeastern University - Boston, MA

**Bachelor of Science in Economics and Mathematics** (December 2019), Northeastern University - Boston, MA
<br />
<br />

#### Interests

- Data Science
- Geospatial Analysis