---
title: "Personal Projects"
output: 
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(htmltools)
source("R/functions.R")
```

<div class='project-row'>
```{r layout='project-card-wrapper'}
create_external_proj_card(
  img_src = "images/bren-leaf-art-small.jpg",
  url = "https://github.com/RHESSysML/RHESSysOutputExplorer",
  button = "View GitHub",
  text = "Understanding Climate Change’s Impact on the Forest Ecosystem: Developing a
Reproducible Machine Learning Approach to Ecohydrologic Model Outputs.",
  text2 = "Machine Learning / Data Visualization",
  text3 = "Capstone Project"
)
```

```{r layout='project-card-wrapper'}
create_external_proj_card(
  img_src = "images/market-area.png",
  url = "https://github.com/alexclippinger/market-area-creator",
  button = "View GitHub",
  text = "Tool to interactively create, view, and download market areas (all destinations that can be reached in a specific amount of time or distance) using the HERE API.",
  text2 = "R Shiny / APIs",
  text3 = "Market Area Creator Tool"
)
```
</div>

<div class='project-row'>
```{r layout='project-card-wrapper'}
create_proj_card(
  img_src = "images/map-preview.png",
  url = "portfolio/2021-12-23-map-collection/index.html",
  button = "View Blog",
  text = "Poster visualizing a backpacking trip on the Big Seki Loop, Kings Canyon National Park.",
  text2 = "Data Visualization / Cartography",
  text3 = "Big Seki Loop Poster"
)
```

```{r layout='project-card-wrapper'}
create_proj_card(
  img_src = "images/crime_map.png",
  url = "portfolio/2021-11-02-sf-crime-and-hilliness/index.html",
  button = "View Blog",
  text = "Does topography have an effect on the likelihood of car break-ins? Using data from San Francisco, CA.",
  text2 = "Linear Regression / Data Analysis",
  text3 = "Regression Analysis of Crime and Topography in San Francisco"
)
```
</div>

<div class='project-row'>
```{r layout='project-card-wrapper'}
create_proj_card(
  img_src = "images/Map 3.png",
  url = "portfolio/2021-12-04-old-lyme-land-trust-gis-overlay-analysis/index.html",
  button = "View Blog",
  text = "Identifying properties with high natural resource values to assist with conservation acquisition targets.",
  text2 = "Spatial Analysis / GIS",
  text3 = "GIS Overlay Analysis for the Old Lyme Land Trust"
)
```

```{r layout='project-card-wrapper'}
create_external_proj_card(
  img_src = "images/Ames_NDWI_Diff.png",
  url = "https://storymaps.arcgis.com/stories/3f4c9e0260e340ec8654e1a4a1417467",
  button = "View Story Map",
  text = "ArcGIS Story Map visualizing the extent of flooding as a result of beaver activity.",
  text2 = "Spatial Analysis / Remote Sensing",
  text3 = "Visualizing Flooding Using NDWI"
)
```
</div>

<div class='project-row'>
```{r layout='project-card-wrapper'}
create_proj_card(
  img_src = "images/ct-audobon.png",
  url = "portfolio/2021-09-20-old-lyme-ospreys-2020-season-review/index.html",
  button = "View Blog",
  text = "Once facing extinction, the Connecticut Osprey population has made a substantial comeback. This blog analyzes the 2020 Osprey Nation Report by the Connecticut Audobon Society.",
  text2 = "Data Analysis / Data Visualization",
  text3 = "Analysis of 2020 Osprey Nation Data"
)
```

```{r layout='project-card-wrapper'}

```
</div>