---
title: "Capstone Project"
description: |
  Understanding Climate Change’s Impact on the Forest Ecosystem: Developing a Reproducible Machine Learning Approach to Ecohydrologic Model Outputs.
authors:
  - first_name: "Alex" 
    last_name: "Clippinger"
    url: https://alexclippinger.github.io
  - first_name: "Peter"
    last_name: "Menzies"
    url: https://petermenzies.github.io
  - first_name: "Wylie"
    last_name: "Hampson"
    url: https://wyliehampson.github.io
  - first_name: "Shale"
    last_name: "Hunter"
    url: https://hub-shale.github.io
timeline: Jan-Jun 2022
output:
  distill::distill_article:
    self_contained: false
citation: false
---


<style>
  .box div {
    display: inline-block;
    text-align: left;
    color: #000000;
  }
  .box h3 {
    padding-bottom: 0px;
  }
  .box h4 {
    padding-bottom: 0px;
  }
  .left {
    vertical-align: top;
    width: 40%;
  }
  .middle {
    vertical-align:top;
    width: 20%;
  }
  .right {
    vertical-align: top;
    width: 20%;
  }
  .break {
    width: 5%;
  }
</style>


<div class="box">
  <h3>Background</h3>
</div>

Ecohydrologic models are core tools when investigating how climate can influence water, carbon, and energy cycles in natural and urbanizing landscapes. RHESSys and other similar models are becoming increasingly sophisticated due to advances in software engineering, increased data availability, and a growing body of knowledge within the field of ecohydrology. Due to the complexity of these models, interpreting the high volume of data they output is a key challenge—both for scientists and the public. Machine learning
algorithms have the capability of quantifying patterns in data that are not revealed by statistical analysis.

<div class="box">
  <div class="left">
  <h3>Role</h3>
  <p>I collaborated with 3 peers to develop and implement a reproducible machine learning algorithm that predicts climate change impact on forest health using RHESSys model output.</p>
  </div>
  <div class="break"></div>
  <div class="middle">
  <h3>Skills</h3>
  <p>R (RStudio)<br/>RShiny<br/>GitHub<br/>Machine Learning</p>
  </div>
  <div class="break"></div>
  <div class="right">
  <h3>Timeline</h3>
  <p>January - June 2022</p>
  </div>
</div>
